### ISSUE TITLE
Not working in anyway

### ISSUE THREAD

**Issue by mildnsj** [alza54/opensource2#4]
![C MWW9)T8 956VEP}}TX)Q](https://github.com/alza54/opensource2/assets/105621500/52e6f5a4-321d-4b63-84a1-f758579804c2)
Everything isn't working, even the speed on watermark.

**Comment by alza54** [comment]
Hello, please try official release f4c781f947dd66ef5797e620797d23b77bd902c0

**Comment by mildnsj** [comment]
> Hello, please try official release [f4c781f](https://github.com/alza54/opensource2/commit/f4c781f947dd66ef5797e620797d23b77bd902c0)

nope its not working either, compile is fixed but none of the features work ingame
have you test it yourself?

**Comment by jumbomumbo111** [comment]
It seems that when manual mapping the graphics hook succeeds but none of the features work, same build file works perfectly with LoadLibrary however.

**Comment by alza54** [comment]
The SDK & all built-in cheats work with LoadDll and LdrpLoadDll injection methods.
LoadLibrary is not the only option. However if you wish to use the SDK with manual map injection, a proposal of appropriate hooking injection methods in a Pull Request is welcomed.

**Comment by JuanUWU69** [comment]
What kind of injector are you using? Been trying a few now but can't seem to find a loadlib injector that works :)

**Comment by kWAYTV** [comment]
> What kind of injector are you using? Been trying a few now but can't seem to find a loadlib injector that works :)

I'm personally using thread hijacking and it works
