### ISSUE TITLE
ESP not working

### ISSUE THREAD

**Issue by Bam810bam321** [alza54/opensource2#8]
Title says it and the aimbot doesn't work so I am guessing the signatures are outdated.

**Comment by alza54** [comment]
Working after https://github.com/alza54/opensource2/commit/7dbb3f4b7b34131da3f543726c3dd989307fff98
Don't use manual mapping if you don't wish to modify the hooking method

**Comment by alza54** [comment]
The base way is to Manual map and edit hooking methods. LdrpLoadDll otherwise maybe

**Comment by Bam810bam321** [comment]
Alright thank you for the info
